module Classifier
  class WordList
    @location_table: Hash[Symbol, Integer]

    def initialize: () -> void

    def add_word: (Symbol word) -> Integer?

    def []: (Symbol lookup) -> Integer?

    def word_for_index: (Integer ind) -> Symbol?

    def size: () -> Integer
  end
end
