module Classifier
  class Bayes
    @categories: Hash[Symbol, Hash[Symbol, Integer]]
    @total_words: Integer
    @category_counts: Hash[Symbol, Integer]
    @category_word_count: Hash[Symbol, Integer]

    def initialize: (*_ToS categories) -> void

    def train: (_ToS category, String text) -> void

    def untrain: (_ToS category, String text) -> void

    def classifications: (String text) -> Hash[String, Float]

    def classify: (String text) -> String

    def categories: () -> Array[String]

    def add_category: (_ToS category) -> Hash[Symbol, Integer]

    alias append_category add_category

    def remove_category: (_ToS category) -> void
  end
end
